version : '3.4'

services:
    model_serving_api:
      build: .
      volumes: 
        - .:/app
      ports: 
        - 8000:8000
      restart: always
      network_mode: host



# docker-compose build
# docker-compose up
# http://localhost:8000/docs#/default/create_file_files__post