FROM python:3.9.12

RUN apt-get update
RUN apt-get install \
    'ffmpeg'\
    'libsm6'\
    'libxext6'  -y
RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu

COPY . .

RUN pip3 install -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "api:app", "--host=0.0.0.0", "--reload"]

# docker build -t facebook-fast-api .
# docker run -p 8000:8000 facebook-fast-api
# http://localhost:8000/docs#/default/create_file_files__post